import type { Metadata } from "next";
import { Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Appbar/Footer";
import Navbar from "@/components/Appbar/Navbar";
import { ThemeModeProvider } from "@/components/ThemeSwitcher";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeModeProvider>
      <html
        lang="en"
        className={`${spaceGrotesk.variable} ${geistMono.variable} h-full antialiased font-body bg-bg bg-stripes overscroll-y-none scroll-smooth`}
      >
        <body className="relative min-h-full flex flex-col pt-32 px-32">
          <div className="container mx-auto">
            <Navbar />
            <main className="relative flex-1 bg-bg-accent bg-noise border border-border">
              <span className="pointer-events-none absolute z-2 -bottom-px left-1/2 -translate-x-1/2 w-screen border-b border-dashed border-border" />
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </ThemeModeProvider>
  );
}
