import type { Metadata } from "next";
import { Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeModeProvider } from "@/components/ThemeSwitcher";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeModeProvider>
      <html
        lang="en"
        className={`${spaceGrotesk.variable} ${geistMono.variable} h-full antialiased font-body bg-bg bg-stripes`}
      >
        <body className="relative min-h-full flex flex-col pt-32 px-32">
          <span className="pointer-events-none absolute left-32 top-0 bottom-0 border-l border-dashed border-border" />
          <span className="pointer-events-none absolute right-32 top-0 bottom-0 border-r border-dashed border-border" />

          <Navbar />
          <main className="relative flex-1 bg-bg-accent bg-noise border border-border">
            <span className="pointer-events-none absolute -top-px left-1/2 -translate-x-1/2 w-screen border-t border-dashed border-border" />
            <span className="pointer-events-none absolute -bottom-px left-1/2 -translate-x-1/2 w-screen border-b border-dashed border-border" />
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ThemeModeProvider>
  );
}
